In [15]:
import numpy as np

data = np.loadtxt('chocolate_rating.csv', delimiter=',')
print('차원:', data.ndim)
print('모양:', data.shape)
print('원소수 :', data.size)

print(data)

#배열 통계: 모든 초콜릿의 평균 평점을 슬라이싱한 넘파이 배열에 통계함수 mean 적용
ratings_mean = data[:,3].mean()
print(ratings_mean)

#우수 초콜릿 번호


차원: 2
모양: (1795, 4)
원소수 : 7180
[[1.000e+00 2.016e+03 6.300e-01 3.750e+00]
 [2.000e+00 2.015e+03 7.000e-01 2.750e+00]
 [3.000e+00 2.015e+03 7.000e-01 3.000e+00]
 ...
 [1.793e+03 2.011e+03 6.500e-01 3.500e+00]
 [1.794e+03 2.011e+03 6.200e-01 3.250e+00]
 [1.795e+03 2.010e+03 6.500e-01 3.000e+00]]
3.185933147632312
